#!/bin/sh

unset ARCH

case "$1" in
    # ppc|powerpc) ARCH=ppc ;;
    # mpc107) ARCH=mpc107 ;;
    # osx|darwin) ARCH=osx ;;
    ppc|powerpc|mpc107|osx|darwin) ARCH=ppc ;;
esac

test "$ARCH" || ARCH=`uname -m | sed -e s/i.86/x86/ -e s/i86pc/x86/ \
	-e s/sun4u/sparc64/ -e s/sparc$/sparc32/ \
	-e s/arm.*/arm/ -e s/sa110/arm/ -e s/x86_64/amd64/ \
	-e "s/Power Macintosh/ppc/"`

echo $ARCH
