\
\ Fcode payload for QEMU VGA graphics card
\
\ This is the Forth source for an Fcode payload to initialise
\ the QEMU VGA graphics card.
\

fcode-version3

\
\ Instead of using fixed values for the framebuffer address and the width
\ and height, grab the ones passed in by QEMU/generated by OpenBIOS
\

: qemu-video-addr
  " qemu-video-addr" $find if
    cell+ @
  then
;

: qemu-video-width
  " qemu-video-width" $find if
    cell+ @
  then
;

: qemu-video-height
  " qemu-video-height" $find if
    cell+ @
  then
;

: qemu-vga-driver-install ( -- )
  qemu-video-addr to frame-buffer-adr
  default-font set-font
  qemu-video-width qemu-video-height over char-width / over char-height /
  fb8-install
;

: qemu-vga-driver-init
  ['] qemu-vga-driver-install is-install
  ;

qemu-vga-driver-init

end0
