/* tag: data types for forth engine
 *
 * This file is autogenerated by types.sh. Do not edit!
 *
 * Copyright (C) 2003 Patrick Mauritz, Stefan Reinauer
 *
 * See the file "COPYING" for further information about
 * the copyright and warranty status of this work.
 */

#ifndef __TYPES_H
#define __TYPES_H

#include <stdint.h>

/* endianess */
#include "autoconf.h"

/* cell based types */

typedef long long     cell;
typedef unsigned long long ucell;
typedef __int128_t   dcell;
typedef __uint128_t ducell;

#define FMT_ucellx  "%016llx"

#define FMT_elf     "%#x"

#define bitspercell	(sizeof(cell)<<3)
#define bitsperdcell	(sizeof(dcell)<<3)

#define BITS		64

/* size named types */

typedef unsigned char   u8;
typedef unsigned short u16;
typedef unsigned int   u32;
typedef unsigned long  u64;

typedef char  		s8;
typedef short		s16;
typedef int		s32;
typedef long		s64;

#endif
